### ISSUE TITLE
addons breaks OAuth on services like Google/Amazon

### ISSUE THREAD

**Issue by nascentt** [ClearURLs/Addon#329]
Love the addon, but after having google login broken for months i eventually tracked it down to clearurls and see people have been reporting it for a year in the reviews https://chrome.google.com/webstore/detail/clearurls/lckanjgmijmafbedllaakclkaicjfmnk
any chance for a fix?

**Comment by ezxpro** [comment]
Came here to say the exact same thing. 

It took me a while to figure out why ClearURL was to blame.

**Comment by DaSandman** [comment]
Not seeing this issue with the Firefox extension.  Google & Amazon login work as expected.

**Comment by nascentt** [comment]
> Not seeing this issue with the Firefox extension.  Google & Amazon login work as expected.  Perhaps try disabling all extensions with the exception of ClearURLs to see if there is a possible negative interaction between ClearURLs and another extension.  

It might be a chrome only issue.

**Comment by KMohZaid** [comment]
> Not seeing this issue with the Firefox extension. Google & Amazon login work as expected. Perhaps try disabling all extensions with the exception of ClearURLs to see if there is a possible negative interaction between ClearURLs and another extension.



> > Not seeing this issue with the Firefox extension.  Google & Amazon login work as expected.  Perhaps try disabling all extensions with the exception of ClearURLs to see if there is a possible negative interaction between ClearURLs and another extension.
> 
> It might be a chrome only issue.

no have issue in firefox. it is extension issue, seems like extension also filter out essential attributes from https://accounts.google.com/signin/oauth/consent/approval

leaves those "?hl=en&_reqid=12345&rt=j"

### Solution : Extension should exclude https://accounts.google.com/signin/oauth/ url from filtering

**Comment by KMohZaid** [comment]
i think this is issue https://github.com/ClearURLs/Addon/blob/master/core_js/google_link_fix.js

**Comment by tristanjahier** [comment]
It took me a while to understand that it was due to this browser extension too. ^^"
Indeed, trying to authenticate to a 3rd party application with Google does not work. I get an error after selecting my Google account and approving.
Disabling the extension before approving solves the problem.

NB: sign-in to Google itself is not broken!

**Comment by farski** [comment]
This has just started happening to me in Firefox, but only on certain Google OAuth flows. For example, Asana, Zoom, Zendesk, AWS SSO all work. Our own authentication system at work, which worked up until at least 23 January, has now started breaking when ClearURLs is enabled.

**Comment by nascentt** [comment]
Any javascript devs able to submit a pull request?  Sadly it looks like this has been abandoned and is breaking too many things that depend on OAuth in it's current state.

**Comment by KMohZaid** [comment]
> > Not seeing this issue with the Firefox extension. Google & Amazon login work as expected. Perhaps try disabling all extensions with the exception of ClearURLs to see if there is a possible negative interaction between ClearURLs and another extension.
> 
> > > Not seeing this issue with the Firefox extension.  Google & Amazon login work as expected.  Perhaps try disabling all extensions with the exception of ClearURLs to see if there is a possible negative interaction between ClearURLs and another extension.
> > 
> > 
> > It might be a chrome only issue.
> 
> no have issue in firefox. it is extension issue, seems like extension also filter out essential attributes from https://accounts.google.com/signin/oauth/consent/approval
> 
> leaves those "?hl=en&_reqid=12345&rt=j"
> 
> ### Solution : Extension should exclude https://accounts.google.com/signin/oauth/ url from filtering


Exceptions i added for google  based filter:
https://accounts.google.com/o/oauth/
https://accounts.google.com/signin/oauth/

And for Global filters :
https://accounts.google.com/

**Comment by KMohZaid** [comment]
>Issue on using my rules : No hash file exists because i am lazy to run pipeline 🙇. So it will requests rules on each startup

To be honest, i am not able to run jobs on gitlab and gitlab UI is confusing for me

**Comment by KMohZaid** [comment]
> Any javascript devs able to submit a pull request? Sadly it looks like this has been abandoned and is breaking too many things that depend on OAuth in it's current state.

last comment : sorry i was busy at that time due to exams and other work.

**Comment by nascentt** [comment]
> > Any javascript devs able to submit a pull request? Sadly it looks like this has been abandoned and is breaking too many things that depend on OAuth in it's current state.
> 
> last comment : sorry i was busy at that time due to exams and other work.

No worries! We all have lives.  Thanks for the pr.

**Comment by nascentt** [comment]
> Some problem i notice in extension while debugging it :
> 1. After url is cleaned, it will change "%20" to " "(space), return and use decoded url
> 2. I am not sure but i notice all special charactor code which starts with %, are decoded in cleaned url not just space? It can cause issue with corrupting legit attributes (ig it was doing this with google oauth)
> 
> 

Oh wow. This sounds like it deserves it's own GitHub issue.

**Comment by KevinRoebert** [comment]
@KMohZaid Thanks for the PR. The issue should be fixed

**Comment by KMohZaid** [comment]
> @KMohZaid Thanks for the PR. The issue should be fixed

Welcome 🤗, also i am thinking to do some more contribution if can

got plenty of time for now

**Comment by lollilol** [comment]
This issue still persists for me when using the Home Assistant "Google Calendar" integration to authenticate with google.

**Comment by KMohZaid** [comment]
> This issue still persists for me when using the Home Assistant "Google Calendar" integration to authenticate with google.
> 
> ![Image](https://github.com/user-attachments/assets/ab9b577f-7999-489a-a839-ad3d86a8d71e)
> 
> it works when disabling ClearURLs Extension

can you send domain of this url?
eg. github.com

**Comment by lollilol** [comment]
> can you send domain of this url? eg. github.com

`https://accounts.google.com/o/oauth2/v2/auth?response_type=code&client_id=680371521533-fpfdomeumia9jama6klkt5vtul4rq5nt.apps.googleusercontent.com&redirect_uri=https://my.home-assistant.io/redirect/oauth&state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmbG93X2lkIjoiMDFKSkRDOEVFVzMzMTcwUThUU0g1SDcyQTMiLCJyZWRpcmVjdF91cmkiOiJodHRwczovL215LmhvbWUtYXNzaXN0YW50LmlvL3JlZGlyZWN0L29hdXRoIn0.hYiw1EMP5oobH9vAwrtVnXpZQeG0jHIO_jW9AqGE5w8&scope=https://www.googleapis.com/auth/calendar&access_type=offline&prompt=consent`

it redirects to

`https://my.home-assistant.io/redirect/oauth/?state=xxx`

**Comment by KMohZaid** [comment]
> > can you send domain of this url? eg. github.com
> 
> ` https://accounts.google.com/o/oauth2/v2/auth?response_type=code&client_id=680371521533-fpfdomeumia9jama6klkt5vtul4rq5nt.apps.googleusercontent.com&redirect_uri=https://my.home-assistant.io/redirect/oauth&state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmbG93X2lkIjoiMDFKSkRDOEVFVzMzMTcwUThUU0g1SDcyQTMiLCJyZWRpcmVjdF91cmkiOiJodHRwczovL215LmhvbWUtYXNzaXN0YW50LmlvL3JlZGlyZWN0L29hdXRoIn0.hYiw1EMP5oobH9vAwrtVnXpZQeG0jHIO_jW9AqGE5w8&scope=https://www.googleapis.com/auth/calendar&access_type=offline&prompt=consent`
> 
> it redirects to
> 
> `https://my.home-assistant.io/redirect/oauth/?state=xxx`

sorry for late response but i think it doesn't filter accounts.google.com
when i tried your given url it gave me different message and when i compared url before going throught clean method and after clean method. they were same

![Image](https://github.com/user-attachments/assets/dbe77aa8-8028-4b0f-9414-ac1652e95be3)


Here see this image where i tested this : 

![Image](https://github.com/user-attachments/assets/3d2a2803-b7ae-4964-8867-0dc086744a4e)

1. i made helper method for me to test cleaning function
```
async function callPureCleaning(url) {
  try {
    let r =  await browser.runtime.sendMessage({
      function: "pureCleaning",
      params: [url],
    });
		console.log(url!=r.response)
		console.log(r.response)
  } catch (error) {
    console.error("Error calling pureCleaning:", error);
    throw error; // Re-throw the error to let the caller handle it
  }
}
```

2. set url 
3.  call, in return it says `false` which indicate no cleaning done
4. replaced domain from `accounts.google.com` to `google.com`
5. call again, still no clean
6. i added google search tracking parameters at end 
7. call again, this time it says `true` means it there was tracking parameter which had to be removed
