### ISSUE TITLE
AliExpress URLs are not being cleared

### ISSUE THREAD

**Issue by RiQuY** [ClearURLs/Addon#81]
AliExpress URLs are not being cleared. I will share an example on how the URL should look.

Shown URL:
```
https://es.aliexpress.com/item/4000672272353.html?pvid=c4cdc770-f05a-4b7b-8a50-d8b81efff6c9&_t=gps-id:pcDetailBottomMoreThisSeller,scm-url:1007.13339.169870.0,pvid:c4cdc770-f05a-4b7b-8a50-d8b81efff6c9,tpp_buckets:668%230%23131923%230_668%23808%234094%23200_668%23888%233325%231_668%232846%238113%23646_668%232717%237558%23188_668%231000022185%231000066059%230_668%233468%2315617%23897
```

Expected result:
```
https://es.aliexpress.com/item/4000672272353.html
```

**Comment by slim8shady9** [comment]
Since nobody cares, can someone explain how to manually create a rule?

**Comment by Tvirin** [comment]
Can anyone work on this one year old issue ?

**Comment by aha999** [comment]
When i saw my link
`https://www.aliexpress.com/item/1005001472307338.html?algo_exp_id=b13fd996-02c2-4b2c-94c9-26ec25eb7f8d-2&pdp_ext_f=%7B%22sku_id%22%3A%2212000016265829061%22%7D&pdp_pi=-1%3B13.8%3B-1%3B2.35%40salePrice%3BEUR%3Bsearch-mainSearch`
I just searched if this issue exists, so here it is... also there is an issue in ClearURLs/Rules here:
https://github.com/ClearURLs/Rules/issues/23

**Comment by RiQuY** [comment]
I closed the issue because I don't want it to appear on my Github anymore, not because of this was solved.

**Comment by Tvirin** [comment]
Why ? It is not possible to solve this issue or it is something else ?

**Comment by aha999** [comment]
@RiQuY you can easily disable your notifications for this issue in the sidebar. The issue should be open as it is not solved. Please reopen. 
![image](https://user-images.githubusercontent.com/50620416/218886025-276e6074-4910-43df-a2c1-0673cef39a8a.png)

**Comment by RiQuY** [comment]
> @RiQuY you can easily disable your notifications for this issue in the sidebar. The issue should be open as it is not solved. Please reopen. ![image](https://user-images.githubusercontent.com/50620416/218886025-276e6074-4910-43df-a2c1-0673cef39a8a.png)

Reopened as you requested, but I don't this make a difference. 4 years have passed with no response.
